import { Language } from './types';

export const LANGUAGES: { code: Language; name: string; flag: string }[] = [
  { code: 'EN', name: 'English', flag: '🇬🇧' },
  { code: 'FR', name: 'Français', flag: '🇫🇷' },
  { code: 'DE', name: 'Deutsch', flag: '🇩🇪' },
  { code: 'ES', name: 'Español', flag: '🇪🇸' },
  { code: 'IT', name: 'Italiano', flag: '🇮🇹' },
  { code: 'PT', name: 'Português', flag: '🇵🇹' },
  { code: 'NL', name: 'Nederlands', flag: '🇳🇱' },
  { code: 'SV', name: 'Svenska', flag: '🇸🇪' },
  { code: 'NO', name: 'Norsk', flag: '🇳🇴' },
  { code: 'DA', name: 'Dansk', flag: '🇩🇰' },
  { code: 'FI', name: 'Suomi', flag: '🇫🇮' },
  { code: 'IS', name: 'Íslenska', flag: '🇮🇸' },
  { code: 'PL', name: 'Polski', flag: '🇵🇱' },
  { code: 'RU', name: 'Русский', flag: '🇷🇺' },
  { code: 'TR', name: 'Türkçe', flag: '🇹🇷' },
  { code: 'EL', name: 'Ελληνικά', flag: '🇬🇷' },
  { code: 'CS', name: 'Čeština', flag: '🇨🇿' },
  { code: 'HU', name: 'Magyar', flag: '🇭🇺' },
  { code: 'RO', name: 'Română', flag: '🇷🇴' },
  { code: 'BG', name: 'Български', flag: '🇧🇬' },
  { code: 'HR', name: 'Hrvatski', flag: '🇭🇷' },
  { code: 'SK', name: 'Slovenčina', flag: '🇸🇰' },
  { code: 'SL', name: 'Slovenščina', flag: '🇸🇮' },
  { code: 'ET', name: 'Eesti', flag: '🇪🇪' },
  { code: 'LV', name: 'Latviešu', flag: '🇱🇻' },
  { code: 'LT', name: 'Lietuvių', flag: '🇱🇹' },
  { code: 'MT', name: 'Malti', flag: '🇲🇹' },
  { code: 'GA', name: 'Gaeilge', flag: '🇮🇪' },
  { code: 'CY', name: 'Cymraeg', flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿' },
  { code: 'SQ', name: 'Shqip', flag: '🇦🇱' },
  { code: 'MK', name: 'Македонски', flag: '🇲🇰' },
];

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  EN: {
    management: 'Management',
    inventory: 'Inventory',
    shop: 'Shop',
    travel: 'Travel',
    staff: 'Staff',
    budget: 'Budget',
    settings: 'Settings',
    open_park: 'Open Park',
    close_park: 'Close Park',
    park_closed: 'Park is Closed',
    park_open: 'Park is Open',
    money: 'Money',
    visitors: 'Visitors',
    happiness: 'Happiness',
    day: 'Day',
    weather: 'Weather',
    travel_to: 'Travel to',
    current_location: 'Current Location',
    home_city: 'Home City',
    dismantle_first: 'Dismantle First',
    island_locked: 'Island Locked',
    apply_now: 'Apply Now',
    total_income: 'Total Income',
    total_expenses: 'Total Expenses',
    net_profit: 'Net Profit',
    language: 'Language',
    music_volume: 'Music Volume',
    sfx_volume: 'SFX Volume',
    reset_game: 'Reset Game',
    confirm_reset: 'Are you sure you want to reset? All progress will be lost.',
    cancel: 'Cancel',
    confirm: 'Confirm',
    park_management: 'Park Management',
    launch_company: 'Launch Company',
    continue_game: 'Continue Existing Game',
    reset_game_confirm: 'Reset Game?',
    yes_reset: 'Yes, Reset',
    back_to_travel: 'Back to Travel List',
    city_center_obstacles: 'City Center Obstacles',
    cloudy: 'Cloudy',
    stormy: 'Stormy',
    needs: 'Needs',
    hunger: 'Hunger',
    bladder: 'Bladder',
    stamina: 'Stamina',
    recent_thoughts: 'Recent Thoughts',
    no_thoughts: 'No thoughts yet...',
    sell: 'Sell',
    deselect: 'Deselect',
    park_stats: 'Park Stats',
    warehouse: 'Warehouse',
    balance: 'Balance',
    exit_zoning: 'Exit Zoning',
    zoning_mode: 'Zoning Mode',
    open_ride_shop: 'Open Ride Shop',
    insufficient_funds: 'Insufficient Funds',
    no_truck_available: 'No Truck Available',
    warehouse_full: 'Warehouse Full',
    purchase_item: 'Purchase Item',
    available_balance: 'Available Balance',
    select_item_to_add: 'Select an item to add it to your inventory',
    company_name: 'Company Name',
    loans: 'Loans',
    daily_net_profit: 'Daily Net Profit',
    visitor_insights: 'Visitor Insights',
    avg_happiness: 'Avg. Happiness',
    avg_spend: 'Avg. Spend',
    recent_performance: 'Recent Performance',
    park_operations: 'Park Operations',
    manual_override: 'Manual Override',
    total_visitors: 'Total Visitors',
    operating_hours: 'Operating Hours',
    open_time: 'Open Time',
    close_time: 'Close Time',
    visitor_demand: 'Visitor Demand',
    standard_entry: 'Standard Entry',
    single_ride_ticket: 'Single Ride Ticket',
    ride_bundle: 'Ride Bundle',
    premium_passes: 'Premium Passes',
    all_day_wristband: 'All-Day Wristband',
    season_pass: 'Season Pass',
    pricing_strategy_tip: 'Pricing Strategy Tip',
    warehouse_capacity: 'Warehouse Capacity',
    warehouse_level: 'Warehouse Level',
    total_staff: 'Total Staff',
    employees: 'Employees',
    morale: 'Morale',
    hourly_payroll: 'Hourly Payroll',
    per_hour: 'per hour',
    recruitment_center: 'Recruitment Center',
    base_salary: 'Base Salary',
    hiring_fee: 'Hiring Fee',
    hire_staff: 'Hire Staff',
    your_team: 'Your Team',
    total_hourly_wage: 'Total Hourly Wage',
    no_staff_hired: 'No staff members currently hired',
    risk_of_quitting: 'Risk of Quitting',
    assigned: 'Assigned',
    upgrade_garage: 'Upgrade Garage',
    max_level_reached: 'Max Level Reached',
    buy_new_truck: 'Buy New Truck',
    cost: 'Cost',
    garage_full: 'Garage Full',
    buy_truck: 'Buy Truck',
    your_trucks: 'Your Trucks',
    transporting: 'Transporting',
    idle: 'Idle',
    no_trucks_in_garage: 'No trucks in your garage',
    travel_to_new_cities: 'Travel to New Cities',
    search_placeholder: 'Search...',
    name: 'Name',
    population: 'Population',
    travel_cost: 'Travel Cost',
    multiplier: 'Multiplier',
    visitors_label: 'Visitors',
    travel_label: 'Travel',
    size: 'Size',
    terrain: 'Terrain',
    pay_off: 'Pay Off',
    available_loan_offers: 'Available Loan Offers',
    day_term: 'Day Term',
    income_today: 'Income (Today)',
    ride_tickets: 'Ride Tickets',
    wristbands_label: 'Wristbands',
    season_passes_label: 'Season Passes',
    ticket_bundles: 'Ticket Bundles',
    food_drinks: 'Food & Drinks',
    other_label: 'Other',
    expenses_today: 'Expenses (Today)',
    staff_wages: 'Staff Wages',
    electricity: 'Electricity',
    loan_interest: 'Loan Interest',
    loan_principal: 'Loan Principal',
    area_rent: 'Area Rent',
    maintenance_label: 'Maintenance',
    upgrade_label: 'Upgrade',
    stored_attractions: 'Stored Attractions',
    warehouse_empty: 'Your warehouse is empty.',
    items_available: 'items available',
    condition_label: 'Condition',
    place_label: 'Place',
    working_label: 'WORKING',
    resting_label: 'RESTING',
    idle_label: 'IDLE',
    lvl_label: 'LVL',
    travel_button: 'Travel',
    home_city_label: 'Home City',
    sound_effects: 'Sound Effects',
    of_potential: 'of potential',
    price_demand_warning: 'Higher prices reduce visitor spawn rate',
    resume_game: 'Resume Game',
    pause_game: 'Pause Game',
    level_label: 'Level',
    status_label: 'Status',
    wait_time: 'Wait Time',
    ticket_price: 'Ticket Price',
    satisfaction_label: 'Satisfaction',
    staff_resting: 'STAFF RESTING',
    repair_button: 'Repair',
    item_price: 'Item Price',
    service_price: 'Service Price',
    too_expensive_warning: 'Visitors might think this is too expensive!',
    fair_price_label: 'A fair price for everyone.',
    dismantle_button: 'Dismantle',
    visitor_label: 'Visitor',
    no_items_message: 'No {intensity} items',
    place_instruction: 'Click on the grid to place your',
    cancel_button: 'Cancel',
    tutorial_step_label: 'Tutorial Step {step}/10',
    skip_button: 'Skip',
    tutorial_title_0: 'Place your first ride',
    tutorial_title_1: 'Create a Truck Zone',
    tutorial_title_2: 'Hire a Ride Operator',
    tutorial_title_3: 'Open the Park',
    tutorial_title_4: 'Earn your first $500',
    tutorial_title_5: 'Build a Food Stall',
    tutorial_title_6: 'Reach 50 Visitors',
    tutorial_title_7: 'Hire a Janitor',
    tutorial_title_8: 'Take a Loan',
    tutorial_title_9: 'Reach 100 Visitors',
    tutorial_desc_0: 'Open your inventory and place the Tea Cups ride near the entrance.',
    tutorial_desc_1: "Select the Zone Tool, choose 'Truck Zone', and draw an area for your trucks.",
    tutorial_desc_2: 'Click on your Tea Cups ride and hire an operator to start running it.',
    tutorial_desc_3: 'Open the Management Panel and toggle the Park Status to Open.',
    tutorial_desc_4: 'Watch the visitors arrive and earn money until your balance reaches $2,500.',
    tutorial_desc_5: 'Visitors get hungry! Place a Hot Dog Stall from your inventory.',
    tutorial_desc_6: 'Keep your park attractive and wait until you have 50 visitors at once.',
    tutorial_desc_7: 'A clean park is a happy park! Go to Management > Staff and hire a Janitor.',
    tutorial_desc_8: 'Need more cash? Go to Management > Loans and take out a Small Business Loan.',
    tutorial_desc_9: 'Grow your park with more rides and stalls to attract 100 visitors simultaneously.',
    reset_confirm_desc: 'This will permanently delete your current company and all progress. This action cannot be undone.',
    weather_sunny: 'Sunny',
    weather_cloudy: 'Cloudy',
    weather_rainy: 'Rainy',
    weather_snowy: 'Snowy',
    weather_freezing: 'Freezing',
    weather_stormy: 'Stormy',
    weather_desc_sunny: 'A beautiful sunny day!',
    weather_desc_cloudy: 'A bit cloudy, but fine for a funfair.',
    weather_desc_rainy: 'Rainy day. Some guests might stay home.',
    weather_desc_snowy: 'Heavy snow! The park must remain closed.',
    weather_desc_freezing: 'Freezing cold! Too dangerous to open.',
    weather_desc_stormy: 'Severe storm! Safety first, park is closed.',
    season_spring: 'Spring',
    season_summer: 'Summer',
    season_autumn: 'Autumn',
    season_winter: 'Winter',
    month_0: 'January',
    month_1: 'February',
    month_2: 'March',
    month_3: 'April',
    month_4: 'May',
    month_5: 'June',
    month_6: 'July',
    month_7: 'August',
    month_8: 'September',
    month_9: 'October',
    month_10: 'November',
    month_11: 'December',
    day_0: 'Sunday',
    day_1: 'Monday',
    day_2: 'Tuesday',
    day_3: 'Wednesday',
    day_4: 'Thursday',
    day_5: 'Friday',
    day_6: 'Saturday',
    zoning_funfair: 'Funfair',
    zoning_truck: 'Truck',
    zoning_staff: 'Staff',
    sell_button: 'Sell',
    place_button: 'Place',
    intensity_gentle: 'Gentle',
    intensity_thrill: 'Thrill',
    intensity_extreme: 'Extreme',
    your_inventory_label: 'Your Inventory',
    all_label: 'All',
    inventory_empty_message: 'Inventory Empty',
    tiles_label: 'Tiles',
    no_trucks_available_message: 'No Trucks Available',
    income_label: 'Income',
    capacity_label: 'Capacity',
    category_ride: 'Ride',
    category_food: 'Food',
    category_facility: 'Facility',
    category_infrastructure: 'Infrastructure',
    shop_cat_all: 'All Items',
    shop_cat_rides: 'Rides',
    shop_cat_food: 'Food & Drink',
    shop_cat_facilities: 'Facilities',
    shop_cat_infrastructure: 'Infrastructure',
    shop_intensity_all: 'All Intensities',
    ride_shop_title: 'Ride Shop',
    thought_not_allowed: "I'm not allowed in there!",
    thought_hungry: "I'm hungry, heading to {rideName}.",
    thought_starving: "I'm starving! Why is there no food in this park?",
    thought_restroom_need: "I really need a restroom...",
    thought_restroom_none: "I can't find a restroom anywhere!",
    thought_tired: "I'm so tired, I need to rest.",
    thought_nowhere_sit: "My feet are killing me, and there's nowhere to sit!",
    thought_price_high: "The price for {rideName} is a bit high...",
    thought_heading_to: "Heading to {rideName}!",
    thought_cant_afford: "I can't afford {rideName}. I need more money.",
    thought_too_expensive: "{rideName} was way too expensive!",
    thought_unsafe: "{rideName} felt unsafe and poorly maintained.",
    thought_no_operator: "There was no one even running {rideName}!",
    thought_fantastic: "That ride on {rideName} was fantastic!",
    thought_out_of_money: "I'm out of money. Time to go home.",
    thought_no_fun: "I'm not having any fun here. I'm leaving.",
    thought_seen_enough: "I've seen enough. Heading out.",
    thought_too_tired_hungry: 'I\'m too tired or hungry to stay any longer.',
    not_set: 'Not Set',
    ride_TEA_CUPS_name: 'Tea Cups',
    ride_FERRIS_WHEEL_name: 'Ferris Wheel',
    ride_BUMPER_CARS_name: 'Bumper Cars',
    ride_CAROUSEL_name: 'Carousel',
    ride_GHOST_TRAIN_name: 'Ghost Train',
    ride_ROLLER_COASTER_name: 'Roller Coaster',
    ride_LOG_FLUME_name: 'Log Flume',
    ride_PIRATE_SHIP_name: 'Pirate Ship',
    ride_DROP_TOWER_name: 'Drop Tower',
    ride_SWING_RIDE_name: 'Swing Ride',
    ride_FOOD_STALL_name: 'Food Stall',
    ride_RESTROOM_name: 'Restroom',
    ride_BENCH_name: 'Bench',
    ride_TRASH_CAN_name: 'Trash Can',
    ride_CLIMBING_WALL_name: 'Climbing Wall',
    ride_SLINGSHOT_name: 'Slingshot',
    ride_TOP_SPIN_name: 'Top Spin',
    ride_ENTERPRISE_name: 'Enterprise',
    ride_WALTZER_name: 'Waltzer',
    ride_HELTER_SKELTER_name: 'Helter Skelter',
    ride_KIDDIE_COASTER_name: 'Kiddie Coaster',
    ride_DUCK_POND_name: 'Duck Pond',
    ride_SHOOTING_GALLERY_name: 'Shooting Gallery',
    ride_COCONUT_SHY_name: 'Coconut Shy',
    ride_STRENGTH_TEST_name: 'Strength Test',
    ride_PONY_TREK_name: 'Pony Trek',
    ride_CARAVAN_name: 'Staff Caravan',
    ride_QUEUE_PATH_name: 'Queue Path',
    staff_OPERATOR_name: 'Ride Operator',
    staff_OPERATOR_desc: 'Required to run rides. Higher level increases ride safety.',
    staff_MECHANIC_name: 'Mechanic',
    staff_MECHANIC_desc: 'Repairs rides and reduces wear and tear.',
    staff_JANITOR_name: 'Janitor',
    staff_JANITOR_desc: 'Keeps the park clean, improving visitor happiness.',
    staff_SECURITY_name: 'Security Guard',
    staff_SECURITY_desc: 'Ensures safety and prevents happiness from dropping too fast.',
    staff_VENDOR_name: 'Vendor',
    staff_VENDOR_desc: 'Increases secondary income from visitors.',
    reason_weather: 'Park is closed due to {weatherType} weather.',
    reason_no_rides: 'No operational rides with operators',
    reason_outside_hours: 'Outside of scheduled hours',
    audio_settings: 'Audio Settings',
    legend_current: 'Current',
    legend_home: 'Home',
    legend_available: 'Available',
    country_UK: 'UK',
    country_FR: 'France',
    country_DE: 'Germany',
    country_ES: 'Spain',
    country_IT: 'Italy',
    country_PT: 'Portugal',
    country_NL: 'Netherlands',
    country_SV: 'Sweden',
    country_NO: 'Norway',
    country_DA: 'Denmark',
    country_FI: 'Finland',
    country_IS: 'Iceland',
    country_PL: 'Poland',
    country_RU: 'Russia',
    country_TR: 'Turkey',
    country_EL: 'Greece',
    country_CS: 'Czech Republic',
    country_HU: 'Hungary',
    country_RO: 'Romania',
    country_BG: 'Bulgaria',
    country_HR: 'Croatia',
    country_SK: 'Slovakia',
    country_SL: 'Slovenia',
    country_ET: 'Estonia',
    country_LV: 'Latvia',
    country_LT: 'Lithuania',
    country_MT: 'Malta',
    country_GA: 'Ireland',
    country_CY: 'Cyprus',
    country_SQ: 'Albania',
    country_MK: 'North Macedonia',
    map_navigation: 'Drag to Pan • Scroll to Zoom',
    potential_destination: 'Potential Destination',
    about: 'About',
    map_size: 'Map Size',
    visitor_multiplier: 'Visitor Multiplier',
    weather_patterns: 'Weather Patterns',
    terrain_PLAINS: 'Plains',
    terrain_COASTAL: 'Coastal',
    terrain_MOUNTAIN: 'Mountain',
    terrain_FOREST: 'Forest',
    terrain_ISLAND: 'Island',
    terrain_URBAN: 'Urban',
    terrain_RIVER: 'River',
    terrain_DESERT: 'Desert',
    terrain_TROPICAL: 'Tropical',
    terrain_ARCTIC: 'Arctic',
    save: 'Save',
    reset: 'Reset',
    close_panel: 'Close Panel',
    active_loans: 'Active Loans',
    no_active_loans: 'No active loans.',
    remaining_principal: 'Remaining Principal',
    interest_rate: 'Interest Rate',
    daily_payment: 'Daily Payment',
    original_amount: 'Original Amount',
    repay_amount: 'Repay ${amount}',
    small_business_loan: 'Small Business Loan',
    expansion_credit: 'Expansion Credit',
    venture_capital: 'Venture Capital',
    today: 'today',
    visitor_stats: 'Visitor Stats',
    pre_opening: 'PRE-OPENING',
    force_park_desc: 'Force the park to open or close regardless of schedule.',
    park_is_open: 'Park is Open',
    park_is_closed: 'Park is Closed',
    attractions: 'Attractions',
    auto_assign: 'Auto-Assign',
    busy_label: 'Busy',
    assigned_label: 'Assigned',
    missing_label: 'Missing',
    hire_operator: 'Hire Operator',
    hire_vendor: 'Hire Vendor',
    hire_mechanic: 'Hire Mechanic',
    mechanic_label: 'Mechanic',
    operator_label: 'Operator',
    vendor_label: 'Vendor',
    auto_assigning: 'Auto-Assigning',
    hourly_salary: 'Hourly Salary',
    underpaid_label: 'Underpaid',
    well_paid_label: 'Well Paid',
    min_label: 'Min',
    max_level: 'Max Level',
    train_button: 'Train (${cost})',
    truck_garage: 'Truck Garage',
    garage_level: 'Garage Level',
    capacity_value: 'Capacity: {current} / {max} Trucks',
    buy_truck_button: 'Buy Truck (${cost})',
    travelling_to: 'Travelling to {city}',
    avoid_obstacles: 'Avoid the obstacles! Hits cost money!',
    search_cities: 'Search cities...',
    tutorial_complete_title: 'Tutorial Complete',
    tutorial_complete_subtitle: "You're ready to go!",
    tutorial_complete_desc: "You've mastered the basics. Now expand your park, travel to new cities, and become a Funfair Tycoon!",
    start_managing: 'Start Managing',
  },
  FR: {
    management: 'Gestion',
    inventory: 'Inventaire',
    shop: 'Boutique',
    travel: 'Voyage',
    staff: 'Personnel',
    budget: 'Budget',
    settings: 'Paramètres',
    open_park: 'Ouvrir le Parc',
    close_park: 'Fermer le Parc',
    park_closed: 'Le Parc est Fermé',
    park_open: 'Le Parc est Ouvert',
    money: 'Argent',
    visitors: 'Visiteurs',
    happiness: 'Bonheur',
    day: 'Jour',
    weather: 'Météo',
    travel_to: 'Voyager vers',
    current_location: 'Lieu Actuel',
    home_city: 'Ville d\'Origine',
    dismantle_first: 'Démonter d\'abord',
    island_locked: 'Île Verrouillée',
    apply_now: 'Postuler Maintenant',
    total_income: 'Revenu Total',
    total_expenses: 'Dépenses Totales',
    net_profit: 'Bénéfice Net',
    language: 'Langue',
    music_volume: 'Volume Musique',
    sfx_volume: 'Volume Effets',
    reset_game: 'Réinitialiser le Jeu',
    confirm_reset: 'Êtes-vous sûr de vouloir réinitialiser ? Toute la progression sera perdue.',
    cancel: 'Annuler',
    confirm: 'Confirmer',
  },
  DE: {
    management: 'Verwaltung',
    inventory: 'Inventar',
    shop: 'Shop',
    travel: 'Reisen',
    staff: 'Personal',
    budget: 'Budget',
    settings: 'Einstellungen',
    open_park: 'Park öffnen',
    close_park: 'Park schließen',
    park_closed: 'Park ist geschlossen',
    park_open: 'Park ist offen',
    money: 'Geld',
    visitors: 'Besucher',
    happiness: 'Zufriedenheit',
    day: 'Tag',
    weather: 'Wetter',
    travel_to: 'Reisen nach',
    current_location: 'Aktueller Standort',
    home_city: 'Heimatstadt',
    dismantle_first: 'Zuerst abbauen',
    island_locked: 'Insel gesperrt',
    apply_now: 'Jetzt bewerben',
    total_income: 'Gesamteinnahmen',
    total_expenses: 'Gesamtausgaben',
    net_profit: 'Nettogewinn',
    language: 'Sprache',
    music_volume: 'Musik Lautstärke',
    sfx_volume: 'SFX Lautstärke',
    reset_game: 'Spiel zurücksetzen',
    confirm_reset: 'Sind Sie sicher, dass Sie zurücksetzen möchten? Alle Fortschritte gehen verloren.',
    cancel: 'Abbrechen',
    confirm: 'Bestätigen',
  },
  ES: {
    management: 'Gestión',
    inventory: 'Inventario',
    shop: 'Tienda',
    travel: 'Viaje',
    staff: 'Personal',
    budget: 'Presupuesto',
    settings: 'Ajustes',
    open_park: 'Abrir Parque',
    close_park: 'Cerrar Parque',
    park_closed: 'Parque Cerrado',
    park_open: 'Parque Abierto',
    money: 'Dinero',
    visitors: 'Visitantes',
    happiness: 'Felicidad',
    day: 'Día',
    weather: 'Clima',
    travel_to: 'Viajar a',
    current_location: 'Ubicación Actual',
    home_city: 'Ciudad Natal',
    dismantle_first: 'Desmantelar Primero',
    island_locked: 'Isla Bloqueada',
    apply_now: 'Aplicar Ahora',
    total_income: 'Ingresos Totales',
    total_expenses: 'Gastos Totales',
    net_profit: 'Beneficio Neto',
    language: 'Idioma',
    music_volume: 'Volumen Música',
    sfx_volume: 'Volumen Efectos',
    reset_game: 'Reiniciar Juego',
    confirm_reset: '¿Estás seguro de que quieres reiniciar? Se perderá todo el progreso.',
    cancel: 'Cancelar',
    confirm: 'Confirmar',
  },
  IT: {
    management: 'Gestione',
    inventory: 'Inventario',
    shop: 'Negozio',
    travel: 'Viaggio',
    staff: 'Personale',
    budget: 'Bilancio',
    settings: 'Impostazioni',
    open_park: 'Apri Parco',
    close_park: 'Chiudi Parco',
    park_closed: 'Il Parco è Chiuso',
    park_open: 'Il Parco è Aperto',
    money: 'Soldi',
    visitors: 'Visitatori',
    happiness: 'Felicità',
    day: 'Giorno',
    weather: 'Meteo',
    travel_to: 'Viaggia verso',
    current_location: 'Posizione Attuale',
    home_city: 'Città d\'Origine',
    dismantle_first: 'Smonta Prima',
    island_locked: 'Isola Bloccata',
    apply_now: 'Applica Ora',
    total_income: 'Entrate Totali',
    total_expenses: 'Uscite Totali',
    net_profit: 'Utile Netto',
    language: 'Lingua',
    music_volume: 'Volume Musica',
    sfx_volume: 'Volume Effetti',
    reset_game: 'Resetta Gioco',
    confirm_reset: 'Sei sicuro di voler resettare? Tutti i progressi andranno persi.',
    cancel: 'Annulla',
    confirm: 'Conferma',
  },
  PT: {
    management: 'Gestão',
    inventory: 'Inventário',
    shop: 'Loja',
    travel: 'Viagem',
    staff: 'Equipa',
    budget: 'Orçamento',
    settings: 'Definições',
    open_park: 'Abrir Parque',
    close_park: 'Fechar Parque',
    park_closed: 'Parque Fechado',
    park_open: 'Parque Aberto',
    money: 'Dinheiro',
    visitors: 'Visitantes',
    happiness: 'Felicidade',
    day: 'Dia',
    weather: 'Clima',
    travel_to: 'Viajar para',
    current_location: 'Localização Atual',
    home_city: 'Cidade Natal',
    dismantle_first: 'Desmontar Primeiro',
    island_locked: 'Ilha Bloqueada',
    apply_now: 'Candidatar Agora',
    total_income: 'Receita Total',
    total_expenses: 'Despesas Totais',
    net_profit: 'Lucro Líquido',
    language: 'Idioma',
    music_volume: 'Volume Música',
    sfx_volume: 'Volume Efeitos',
    reset_game: 'Reiniciar Jogo',
    confirm_reset: 'Tem a certeza que quer reiniciar? Todo o progresso será perdido.',
    cancel: 'Cancelar',
    confirm: 'Confirmar',
  },
  NL: {
    management: 'Beheer',
    inventory: 'Voorraad',
    shop: 'Winkel',
    travel: 'Reizen',
    staff: 'Personeel',
    budget: 'Budget',
    settings: 'Instellingen',
    open_park: 'Park Openen',
    close_park: 'Park Sluiten',
    park_closed: 'Park is Gesloten',
    park_open: 'Park is Open',
    money: 'Geld',
    visitors: 'Bezoekers',
    happiness: 'Geluk',
    day: 'Dag',
    weather: 'Weer',
    travel_to: 'Reizen naar',
    current_location: 'Huidige Locatie',
    home_city: 'Thuisstad',
    dismantle_first: 'Eerst Slopen',
    island_locked: 'Eiland Vergrendeld',
    apply_now: 'Nu Toepassen',
    total_income: 'Totale Inkomsten',
    total_expenses: 'Totale Uitgaven',
    net_profit: 'Nettowinst',
    language: 'Taal',
    music_volume: 'Muziekvolume',
    sfx_volume: 'SFX-volume',
    reset_game: 'Spel Resetten',
    confirm_reset: 'Weet je zeker dat je wilt resetten? Alle voortgang gaat verloren.',
    cancel: 'Annuleren',
    confirm: 'Bevestigen',
  },
  SV: {
    management: 'Hantering',
    inventory: 'Lager',
    shop: 'Butik',
    travel: 'Resa',
    staff: 'Personal',
    budget: 'Budget',
    settings: 'Inställningar',
    open_park: 'Öppna Parken',
    close_park: 'Stäng Parken',
    park_closed: 'Parken är stängd',
    park_open: 'Parken är öppen',
    money: 'Pengar',
    visitors: 'Besökare',
    happiness: 'Glädje',
    day: 'Dag',
    weather: 'Väder',
    travel_to: 'Res till',
    current_location: 'Nuvarande plats',
    home_city: 'Hemstad',
    dismantle_first: 'Montera ner först',
    island_locked: 'Ön är låst',
    apply_now: 'Ansök nu',
    total_income: 'Total inkomst',
    total_expenses: 'Totala utgifter',
    net_profit: 'Nettovinst',
    language: 'Språk',
    music_volume: 'Musikvolym',
    sfx_volume: 'SFX-volym',
    reset_game: 'Återställ spel',
    confirm_reset: 'Är du säker på att du vill återställa? Alla framsteg går förlorade.',
    cancel: 'Avbryt',
    confirm: 'Bekräfta',
    city_name_tromso: 'Tromsø',
    city_desc_tromso: 'Porten till Arktis, känd för norrsken.',
    city_name_bodo: 'Bodø',
    city_desc_bodo: 'En stad strax norr om polcirkeln, känd för sina starka vindar.',
    city_name_sandefjord: 'Sandefjord',
    city_desc_sandefjord: 'En kuststad med en rik valfångsthistoria.',
    city_name_larvik: 'Larvik',
    city_desc_larvik: 'En kuststad känd för sina naturliga källor och bokskog.',
    city_name_arendal: 'Arendal',
    city_desc_arendal: 'En charmig kuststad med en vacker skärgård.',
    city_name_tonsberg: 'Tønsberg',
    city_desc_tonsberg: 'Norges äldsta stad, med ett rikt vikingaarv.',
    city_name_porsgrunn: 'Porsgrunn',
    city_desc_porsgrunn: 'En industristad känd för sin porslinsfabrik.',
    city_name_haugesund: 'Haugesund',
    city_desc_haugesund: 'En kuststad känd för sin vikingahistoria och filmfestival.',
    city_name_moss: 'Moss',
    city_desc_moss: 'En kuststad med en stark industriell och konstnärlig tradition.',
    city_name_hamar: 'Hamar',
    city_desc_hamar: 'Beläget vid Mjøsas stränder, känd för sina domkyrkoruiner.',
    city_name_karlstad: 'Karlstad',
    city_desc_karlstad: 'Solens stad vid Vänerns stränder.',
    city_name_vaxjo: 'Växjö',
    city_desc_vaxjo: 'Europas grönaste stad, omgiven av sjöar och skogar.',
    city_name_halmstad: 'Halmstad',
    city_desc_halmstad: 'Ett populärt sommarmål med vackra stränder.',
    city_name_sundsvall: 'Sundsvall',
    city_desc_sundsvall: 'Stenstaden, återuppbyggd i sten efter en förödande brand.',
    city_name_lulea: 'Luleå',
    city_desc_lulea: 'En kuststad i norr, känd för sitt tekniska universitet.',
    city_name_ostersund: 'Östersund',
    city_desc_ostersund: 'Vinterstaden, belägen vid Storsjöns stränder.',
    city_name_trollhattan: 'Trollhättan',
    city_desc_trollhattan: 'Känd för sina vattenfall och filmindustri.',
    city_name_skovde: 'Skövde',
    city_desc_skovde: 'En stad med ett starkt militärt och industriellt arv.',
    city_name_uddevalla: 'Uddevalla',
    city_desc_uddevalla: 'Hjärtat av Bohuslän, med en vacker kustlinje.',
    city_name_varberg: 'Varberg',
    city_desc_varberg: 'En populär kurort med en historisk fästning.',
    city_name_silkeborg: 'Silkeborg',
    city_desc_silkeborg: 'Beläget i hjärtat av sjödistriktet, omgivet av skogar.',
    city_name_fredericia: 'Fredericia',
    city_desc_fredericia: 'En historisk fästningsstad med en unik rutnätslayout.',
    city_name_holstebro: 'Holstebro',
    city_desc_holstebro: 'Ett kulturellt nav i Västjylland med många skulpturer.',
    city_name_slagelse: 'Slagelse',
    city_desc_slagelse: 'En historisk stad på Själland, nära Stora Bält-bron.',
    city_name_hillerod: 'Hillerød',
    city_desc_hillerod: 'Hem till det magnifika Frederiksborgs slott.',
    city_name_sonderborg: 'Sønderborg',
    city_desc_sonderborg: 'En historisk stad på ön Als, nära den tyska gränsen.',
    city_name_svendborg: 'Svendborg',
    city_desc_svendborg: 'En sjöfartsstad på Fyn, porten till skärgården.',
    city_name_hjorring: 'Hjørring',
    city_desc_hjorring: 'Huvudstaden i Vendsyssel i Nordjylland.',
    city_name_frederikshavn: 'Frederikshavn',
    city_desc_frederikshavn: 'En stor färjehamn som förbinder Danmark med Norge och Sverige.',
    city_name_naestved: 'Næstved',
    city_desc_naestved: 'En historisk stad på Sydsjälland med ett charmigt centrum.',
    city_name_joensuu: 'Joensuu',
    city_desc_joensuu: 'Huvudstaden i Norra Karelen, en stad av skogar och vatten.',
    city_name_lappeenranta: 'Villmanstrand',
    city_desc_lappeenranta: 'En sjöstad nära den ryska gränsen, känd för sin fästning.',
    city_name_hameenlinna: 'Tavastehus',
    city_desc_hameenlinna: 'En historisk stad med ett medeltida slott, Sibelius födelseplats.',
    city_name_vaasa: 'Vasa',
    city_desc_vaasa: 'En kuststad med ett starkt svenskspråkigt inflytande.',
    city_name_seinajoki: 'Seinäjoki',
    city_desc_seinajoki: 'En stad känd för sina sommarfestivaler och Aalto-arkitektur.',
    city_name_rovaniemi: 'Rovaniemi',
    city_desc_rovaniemi: 'Tomtens officiella hemstad vid polcirkeln.',
    city_name_mikkeli: 'Sankt Michel',
    city_desc_mikkeli: 'En stad i hjärtat av sjödistriktet, känd för sin historia.',
    city_name_kotka: 'Kotka',
    city_desc_kotka: 'En sjöfartsstad vid Finska viken, känd för sina parker.',
    city_name_salo: 'Salo',
    city_desc_salo: 'En stad med en stark historia inom elektronikindustrin.',
    city_name_porvoo: 'Borgå',
    city_desc_porvoo: 'En charmig historisk stad med röda trähus.',
    city_name_gardabaer: 'Garðabær',
    city_desc_gardabaer: 'En växande kommun i huvudstadsregionen.',
    city_name_mosfellsbaer: 'Mosfellsbær',
    city_desc_mosfellsbaer: 'En stad känd för sin naturliga skönhet och vandringsleder.',
    city_name_akranes: 'Akranes',
    city_desc_akranes: 'En hamnstad med en lång historia av fiske och industri.',
    city_name_selfoss: 'Selfoss',
    city_desc_selfoss: 'Den största staden på södra Island, ett nav för regionen.',
    city_name_seltjarnarnes: 'Seltjarnarnes',
    city_desc_seltjarnarnes: 'En liten stad på en halvö bredvid Reykjavík.',
    city_name_vestmannaeyjar: 'Västmannaöarna',
    city_desc_vestmannaeyjar: 'En skärgård utanför sydkusten, känd för sina vulkaner.',
    city_name_isafjordur: 'Ísafjörður',
    city_desc_isafjordur: 'Den största staden i Västfjordarna, omgiven av branta berg.',
    city_name_saudarkrokur: 'Sauðárkrókur',
    city_desc_saudarkrokur: 'En stad på norra Island, känd för sin historia och hästar.',
    city_name_egilsstadir: 'Egilsstaðir',
    city_desc_egilsstadir: 'Huvudnavet på östra Island, beläget vid en flods stränder.',
    city_name_husavik: 'Húsavík',
    city_desc_husavik: 'Islands valskådningshuvudstad.',
  },
  NO: {
    management: 'Ledelse',
    inventory: 'Lager',
    shop: 'Butikk',
    travel: 'Reise',
    staff: 'Ansatte',
    budget: 'Budsjett',
    settings: 'Innstillinger',
    open_park: 'Åpne parken',
    close_park: 'Steng parken',
    park_closed: 'Parken er stengt',
    park_open: 'Parken er åpen',
    money: 'Penger',
    visitors: 'Besøkende',
    happiness: 'Glede',
    day: 'Dag',
    weather: 'Vær',
    travel_to: 'Reis til',
    current_location: 'Nåværende posisjon',
    home_city: 'Hjemby',
    dismantle_first: 'Demonter først',
    island_locked: 'Øya er låst',
    apply_now: 'Søk nå',
    total_income: 'Total inntekt',
    total_expenses: 'Total utgifter',
    net_profit: 'Nettoprofitt',
    language: 'Språk',
    music_volume: 'Musikkvolum',
    sfx_volume: 'SFX-volum',
    reset_game: 'Nullstill spill',
    confirm_reset: 'Er du sikker på at du vil nullstille? All fremgang vil gå tapt.',
    cancel: 'Avbryt',
    confirm: 'Bekreft',
    city_name_tromso: 'Tromsø',
    city_desc_tromso: 'Porten til Arktis, kjent for nordlys.',
    city_name_bodo: 'Bodø',
    city_desc_bodo: 'En by rett nord for polarsirkelen, kjent for sin sterke vind.',
    city_name_sandefjord: 'Sandefjord',
    city_desc_sandefjord: 'En kystby med en rik hvalfangsthistorie.',
    city_name_larvik: 'Larvik',
    city_desc_larvik: 'En kystby kjent for sine naturlige kilder og bøkeskog.',
    city_name_arendal: 'Arendal',
    city_desc_arendal: 'En sjarmerende kystby med en vakker skjærgård.',
    city_name_tonsberg: 'Tønsberg',
    city_desc_tonsberg: 'Norges eldste by, med en rik vikingarv.',
    city_name_porsgrunn: 'Porsgrunn',
    city_desc_porsgrunn: 'En industriby kjent for sin porselensfabrikk.',
    city_name_haugesund: 'Haugesund',
    city_desc_haugesund: 'En kystby kjent for sin vikinghistorie og filmfestival.',
    city_name_moss: 'Moss',
    city_desc_moss: 'En kystby med en sterk industriell og kunstnerisk tradisjon.',
    city_name_hamar: 'Hamar',
    city_desc_hamar: 'Ligger ved bredden av Mjøsa, kjent for sine katedralruiner.',
    city_name_karlstad: 'Karlstad',
    city_desc_karlstad: 'Solskinnets by ved bredden av innsjøen Vänern.',
    city_name_vaxjo: 'Växjö',
    city_desc_vaxjo: 'Europas grønneste by, omgitt av innsjøer og skoger.',
    city_name_halmstad: 'Halmstad',
    city_desc_halmstad: 'Et populært sommarmål med vakre strender.',
    city_name_sundsvall: 'Sundsvall',
    city_desc_sundsvall: 'Steinstaden, gjenoppbygd i stein etter en ødeleggende brann.',
    city_name_lulea: 'Luleå',
    city_desc_lulea: 'En kystby i nord, kjent for sitt tekniske universitet.',
    city_name_ostersund: 'Östersund',
    city_desc_ostersund: 'Vinterbyen, beliggende ved bredden av Storsjön.',
    city_name_trollhattan: 'Trollhättan',
    city_desc_trollhattan: 'Kjent for sine fosser og filmindustri.',
    city_name_skovde: 'Skövde',
    city_desc_skovde: 'En by med en sterk militær og industriell arv.',
    city_name_uddevalla: 'Uddevalla',
    city_desc_uddevalla: 'Hjertet av Bohuslän, med en vakker kystlinje.',
    city_name_varberg: 'Varberg',
    city_desc_varberg: 'En populær kurby med en historisk festning.',
    city_name_silkeborg: 'Silkeborg',
    city_desc_silkeborg: 'Ligger i hjertet av innsjødistriktet, omgitt av skoger.',
    city_name_fredericia: 'Fredericia',
    city_desc_fredericia: 'En historisk festningsby med en unik rutenettoppsett.',
    city_name_holstebro: 'Holstebro',
    city_desc_holstebro: 'Et kulturelt knutepunkt i Vestjylland med mange skulpturer.',
    city_name_slagelse: 'Slagelse',
    city_desc_slagelse: 'En historisk by på Sjælland, nær Storebæltsbroen.',
    city_name_hillerod: 'Hillerød',
    city_desc_hillerod: 'Hjem til det praktfulle Frederiksborg slott.',
    city_name_sonderborg: 'Sønderborg',
    city_desc_sonderborg: 'En historisk by på øya Als, nær den tyske grensen.',
    city_name_svendborg: 'Svendborg',
    city_desc_svendborg: 'En sjøfartsby på Fyn, porten til skjærgården.',
    city_name_hjorring: 'Hjørring',
    city_desc_hjorring: 'Hovedstaden i Vendsyssel i Nordjylland.',
    city_name_frederikshavn: 'Frederikshavn',
    city_desc_frederikshavn: 'En stor fergehavn som forbinder Danmark med Norge og Sverige.',
    city_name_naestved: 'Næstved',
    city_desc_naestved: 'En historisk by på Sør-Sjælland med et sjarmerende sentrum.',
    city_name_joensuu: 'Joensuu',
    city_desc_joensuu: 'Hovedstaden i Nord-Karelen, en by med skog og vann.',
    city_name_lappeenranta: 'Villmanstrand',
    city_desc_lappeenranta: 'En by ved innsjøen nær den russiske grensen, kjent for sin festning.',
    city_name_hameenlinna: 'Tavastehus',
    city_desc_hameenlinna: 'En historisk by med et middelalderslott, Sibelius\' fødested.',
    city_name_vaasa: 'Vasa',
    city_desc_vaasa: 'En kystby med en sterk svensktalende innflytelse.',
    city_name_seinajoki: 'Seinäjoki',
    city_desc_seinajoki: 'En by kjent for sine sommerfestivaler og Aalto-arkitektur.',
    city_name_rovaniemi: 'Rovaniemi',
    city_desc_rovaniemi: 'Julenissens offisielle hjemby ved polarsirkelen.',
    city_name_mikkeli: 'Sankt Michel',
    city_desc_mikkeli: 'En by i hjertet av innsjødistriktet, kjent for sin historie.',
    city_name_kotka: 'Kotka',
    city_desc_kotka: 'En sjøfartsby ved Finskebukta, kjent for sine parker.',
    city_name_salo: 'Salo',
    city_desc_salo: 'En by med en sterk historie innen elektronikkindustrien.',
    city_name_porvoo: 'Borgå',
    city_desc_porvoo: 'En sjarmerende historisk by med røde trehus.',
    city_name_gardabaer: 'Garðabær',
    city_desc_gardabaer: 'En voksende kommune i hovedstadsregionen.',
    city_name_mosfellsbaer: 'Mosfellsbær',
    city_desc_mosfellsbaer: 'En by kjent for sin naturlige skjønnhet og turstier.',
    city_name_akranes: 'Akranes',
    city_desc_akranes: 'En havneby med en lang historie med fiske og industri.',
    city_name_selfoss: 'Selfoss',
    city_desc_selfoss: 'Den største byen på Sør-Island, et knutepunkt for regionen.',
    city_name_seltjarnarnes: 'Seltjarnarnes',
    city_desc_seltjarnarnes: 'En liten by på en halvøy ved siden av Reykjavík.',
    city_name_vestmannaeyjar: 'Vestmannaeyjar',
    city_desc_vestmannaeyjar: 'En øygruppe utenfor sørkysten, kjent for sine vulkaner.',
    city_name_isafjordur: 'Ísafjörður',
    city_desc_isafjordur: 'Den største byen i Vestfjordene, omgitt av bratte fjell.',
    city_name_saudarkrokur: 'Sauðárkrókur',
    city_desc_saudarkrokur: 'En by på Nord-Island, kjent for sin historie og hester.',
    city_name_egilsstadir: 'Egilsstaðir',
    city_desc_egilsstadir: 'Hovedknutepunktet på Øst-Island, beliggende ved bredden av en elv.',
    city_name_husavik: 'Húsavík',
    city_desc_husavik: 'Islands hvalsafarihovedstad.',
  },
  DA: {
    management: 'Ledelse',
    inventory: 'Lager',
    shop: 'Butik',
    travel: 'Rejse',
    staff: 'Personale',
    budget: 'Budget',
    settings: 'Indstillinger',
    open_park: 'Åbn parken',
    close_park: 'Luk parken',
    park_closed: 'Parken er lukket',
    park_open: 'Parken er åben',
    money: 'Penge',
    visitors: 'Besøgende',
    happiness: 'Glæde',
    day: 'Dag',
    weather: 'Vejr',
    travel_to: 'Rejs til',
    current_location: 'Nuværende placering',
    home_city: 'Hjemby',
    dismantle_first: 'Afmonter først',
    island_locked: 'Øen er låst',
    apply_now: 'Ansøg nu',
    total_income: 'Samlet indkomst',
    total_expenses: 'Samlede udgifter',
    net_profit: 'Nettooverskud',
    language: 'Sprog',
    music_volume: 'Musiklydstyrke',
    sfx_volume: 'SFX-lydstyrke',
    reset_game: 'Nulstil spil',
    confirm_reset: 'Er du sikker på, at du vil nulstille? Alle fremskridt går tabt.',
    cancel: 'Annuller',
    confirm: 'Bekræft',
    city_name_tromso: 'Tromsø',
    city_desc_tromso: 'Porten til Arktis, berømt for nordlys.',
    city_name_bodo: 'Bodø',
    city_desc_bodo: 'En by lige nord for polarcirklen, kendt for sin stærke vind.',
    city_name_sandefjord: 'Sandefjord',
    city_desc_sandefjord: 'En kystby med en rig hvalfangsthistorie.',
    city_name_larvik: 'Larvik',
    city_desc_larvik: 'En kystby kendt for sine naturlige kilder og bøgeskov.',
    city_name_arendal: 'Arendal',
    city_desc_arendal: 'En charmerende kystby med en smuk skærgård.',
    city_name_tonsberg: 'Tønsberg',
    city_desc_tonsberg: 'Norges ældste by med en rig vikingearv.',
    city_name_porsgrunn: 'Porsgrunn',
    city_desc_porsgrunn: 'En industriby kendt for sin porcelænsfabrik.',
    city_name_haugesund: 'Haugesund',
    city_desc_haugesund: 'En kystby kendt for sin vikingehistorie og filmfestival.',
    city_name_moss: 'Moss',
    city_desc_moss: 'En kystby med en stærk industriel og kunstnerisk tradition.',
    city_name_hamar: 'Hamar',
    city_desc_hamar: 'Beliggende ved bredden af Mjøsa, kendt for sine katedralruiner.',
    city_name_karlstad: 'Karlstad',
    city_desc_karlstad: 'Solskinets by ved bredden af søen Vänern.',
    city_name_vaxjo: 'Växjö',
    city_desc_vaxjo: 'Europas grønneste by, omgivet af søer og skove.',
    city_name_halmstad: 'Halmstad',
    city_desc_halmstad: 'Et populært sommermål med smukke strande.',
    city_name_sundsvall: 'Sundsvall',
    city_desc_sundsvall: 'Stenbyen, genopbygget i sten efter en ødelæggende brand.',
    city_name_lulea: 'Luleå',
    city_desc_lulea: 'En kystby i nord, kendt for sit tekniske universitet.',
    city_name_ostersund: 'Östersund',
    city_desc_ostersund: 'Vinterbyen, beliggende ved bredden af Storsjön.',
    city_name_trollhattan: 'Trollhättan',
    city_desc_trollhattan: 'Kendt for sine vandfald og filmindustri.',
    city_name_skovde: 'Skövde',
    city_desc_skovde: 'En by med en stærk militær og industriel arv.',
    city_name_uddevalla: 'Uddevalla',
    city_desc_uddevalla: 'Hjertet af Bohuslän med en smuk kystlinje.',
    city_name_varberg: 'Varberg',
    city_desc_varberg: 'En populær kurby med en historisk fæstning.',
    city_name_silkeborg: 'Silkeborg',
    city_desc_silkeborg: 'Beliggende i hjertet af sødistriktet, omgivet af skove.',
    city_name_fredericia: 'Fredericia',
    city_desc_fredericia: 'En historisk fæstningsby med et unikt gitterlayout.',
    city_name_holstebro: 'Holstebro',
    city_desc_holstebro: 'Et kulturelt knudepunkt i Vestjylland med mange skulpturer.',
    city_name_slagelse: 'Slagelse',
    city_desc_slagelse: 'En historisk by på Sjælland, nær Storebæltsbroen.',
    city_name_hillerod: 'Hillerød',
    city_desc_hillerod: 'Hjemsted for det storslåede Frederiksborg Slot.',
    city_name_sonderborg: 'Sønderborg',
    city_desc_sonderborg: 'En historisk by på øen Als, nær den tyske grænse.',
    city_name_svendborg: 'Svendborg',
    city_desc_svendborg: 'En søfartsby på Fyn, porten til øhavet.',
    city_name_hjorring: 'Hjørring',
    city_desc_hjorring: 'Hovedstaden i Vendsyssel i Nordjylland.',
    city_name_frederikshavn: 'Frederikshavn',
    city_desc_frederikshavn: 'En stor færgehavn, der forbinder Danmark med Norge og Sverige.',
    city_name_naestved: 'Næstved',
    city_desc_naestved: 'En historisk by på Sydsjælland med et charmerende centrum.',
    city_name_joensuu: 'Joensuu',
    city_desc_joensuu: 'Hovedstaden i Nordkarelen, en by med skov og vand.',
    city_name_lappeenranta: 'Villmanstrand',
    city_desc_lappeenranta: 'En by ved søen nær den russiske grænse, kendt for sin fæstning.',
    city_name_hameenlinna: 'Tavastehus',
    city_desc_hameenlinna: 'En historisk by med et middelalderslot, Sibelius\' fødested.',
    city_name_vaasa: 'Vasa',
    city_desc_vaasa: 'En kystby med en stærk svensktalende indflydelse.',
    city_name_seinajoki: 'Seinäjoki',
    city_desc_seinajoki: 'En by kendt for sine sommerfestivaler og Aalto-arkitektur.',
    city_name_rovaniemi: 'Rovaniemi',
    city_desc_rovaniemi: 'Julemandens officielle hjemby ved polarcirklen.',
    city_name_mikkeli: 'Sankt Michel',
    city_desc_mikkeli: 'En by i hjertet af sødistriktet, kendt for sin historie.',
    city_name_kotka: 'Kotka',
    city_desc_kotka: 'En søfartsby ved den Finske Bugt, kendt for sine parker.',
    city_name_salo: 'Salo',
    city_desc_salo: 'En by med en stærk historie inden for elektronikindustrien.',
    city_name_porvoo: 'Borgå',
    city_desc_porvoo: 'En charmerende historisk by med røde træhuse.',
    city_name_gardabaer: 'Garðabær',
    city_desc_gardabaer: 'En voksende kommune i hovedstadsregionen.',
    city_name_mosfellsbaer: 'Mosfellsbær',
    city_desc_mosfellsbaer: 'En by kendt for sin naturlige skønhed og vandrestier.',
    city_name_akranes: 'Akranes',
    city_desc_akranes: 'En havneby med en lang historie med fiskeri og industri.',
    city_name_selfoss: 'Selfoss',
    city_desc_selfoss: 'Den største by i det sydlige Island, et knudepunkt for regionen.',
    city_name_seltjarnarnes: 'Seltjarnarnes',
    city_desc_seltjarnarnes: 'En lille by på en halvø ved siden af Reykjavík.',
    city_name_vestmannaeyjar: 'Vestmannaøerne',
    city_desc_vestmannaeyjar: 'En øgruppe ud for sydkysten, kendt for sine vulkaner.',
    city_name_isafjordur: 'Ísafjörður',
    city_desc_isafjordur: 'Den største by i Vestfjordene, omgivet af stejle bjerge.',
    city_name_saudarkrokur: 'Sauðárkrókur',
    city_desc_saudarkrokur: 'En by i det nordlige Island, kendt for sin historie og heste.',
    city_name_egilsstadir: 'Egilsstaðir',
    city_desc_egilsstadir: 'Hovedknudepunktet i det østlige Island, beliggende ved bredden af en flod.',
    city_name_husavik: 'Húsavík',
    city_desc_husavik: 'Islands hvalsafari-hovedstad.',
  },
  FI: {
    management: 'Hallinta',
    inventory: 'Varasto',
    shop: 'Kauppa',
    travel: 'Matkusta',
    staff: 'Henkilökunta',
    budget: 'Budjetti',
    settings: 'Asetukset',
    open_park: 'Avaa puisto',
    close_park: 'Sulje puisto',
    park_closed: 'Puisto on suljettu',
    park_open: 'Puisto on auki',
    money: 'Raha',
    visitors: 'Vierailijat',
    happiness: 'Onnellisuus',
    day: 'Päivä',
    weather: 'Sää',
    travel_to: 'Matkusta kohteeseen',
    current_location: 'Nykyinen sijainti',
    home_city: 'Kotikaupunki',
    dismantle_first: 'Pura ensin',
    island_locked: 'Saari lukittu',
    apply_now: 'Hae nyt',
    total_income: 'Tulot yhteensä',
    total_expenses: 'Menot yhteensä',
    net_profit: 'Nettovoitto',
    language: 'Kieli',
    music_volume: 'Musiikin voimakkuus',
    sfx_volume: 'SFX-voimakkuus',
    reset_game: 'Nollaa peli',
    confirm_reset: 'Haluatko varmasti nollata? Kaikki edistyminen menetetään.',
    cancel: 'Peruuta',
    confirm: 'Vahvista',
    city_name_tromso: 'Tromssa',
    city_desc_tromso: 'Portti Arktikselle, kuuluisa revontulista.',
    city_name_bodo: 'Bodø',
    city_desc_bodo: 'Kaupunki aivan napapiirin pohjoispuolella, tunnettu voimakkaista tuulistaan.',
    city_name_sandefjord: 'Sandefjord',
    city_desc_sandefjord: 'Rannikkokaupunki, jolla on rikas valaanpyyntihistoria.',
    city_name_larvik: 'Larvik',
    city_desc_larvik: 'Rannikkokaupunki, joka tunnetaan luonnonlähteistään ja pyökkimetsistään.',
    city_name_arendal: 'Arendal',
    city_desc_arendal: 'Viehättävä rannikkokaupunki, jolla on kaunis saaristo.',
    city_name_tonsberg: 'Tønsberg',
    city_desc_tonsberg: 'Norjan vanhin kaupunki, jolla on rikas viikinkiperintö.',
    city_name_porsgrunn: 'Porsgrunn',
    city_desc_porsgrunn: 'Teollisuuskaupunki, joka tunnetaan posliinitehtaastaan.',
    city_name_haugesund: 'Haugesund',
    city_desc_haugesund: 'Rannikkokaupunki, joka tunnetaan viikinkihistoriastaan ja elokuvajuhlistaan.',
    city_name_moss: 'Moss',
    city_desc_moss: 'Rannikkokaupunki, jolla on vahva teollinen ja taiteellinen perinne.',
    city_name_hamar: 'Hamar',
    city_desc_hamar: 'Sijaitsee Mjøsa-järven rannalla, tunnettu katedraalin raunioista.',
    city_name_karlstad: 'Karlstad',
    city_desc_karlstad: 'Auringonpaisteen kaupunki Vänern-järven rannalla.',
    city_name_vaxjo: 'Växjö',
    city_desc_vaxjo: 'Euroopan vihrein kaupunki, järvien ja metsien ympäröimä.',
    city_name_halmstad: 'Halmstad',
    city_desc_halmstad: 'Suosittu kesäkohde, jossa on kauniita rantoja.',
    city_name_sundsvall: 'Sundsvall',
    city_desc_sundsvall: 'Kivikaupunki, joka rakennettiin uudelleen kivestä tuhoisan tulipalon jälkeen.',
    city_name_lulea: 'Luulaja',
    city_desc_lulea: 'Rannikkokaupunki pohjoisessa, tunnettu teknillisestä yliopistostaan.',
    city_name_ostersund: 'Östersund',
    city_desc_ostersund: 'Talvikaupunki, joka sijaitsee Storsjön-järven rannalla.',
    city_name_trollhattan: 'Trollhättan',
    city_desc_trollhattan: 'Tunnettu vesiputouksistaan ja elokuvateollisuudestaan.',
    city_name_skovde: 'Skövde',
    city_desc_skovde: 'Kaupunki, jolla on vahva sotilaallinen ja teollinen perintö.',
    city_name_uddevalla: 'Uddevalla',
    city_desc_uddevalla: 'Bohusläni sydän, jolla on kaunis rannikko.',
    city_name_varberg: 'Varberg',
    city_desc_varberg: 'Suosittu kylpyläkaupunki, jossa on historiallinen linnoitus.',
    city_name_silkeborg: 'Silkeborg',
    city_desc_silkeborg: 'Sijaitsee Järvi-Suomen sydämessä, metsien ympäröimänä.',
    city_name_fredericia: 'Fredericia',
    city_desc_fredericia: 'Historiallinen linnoituskaupunki, jolla on ainutlaatuinen ruutukaava.',
    city_name_holstebro: 'Holstebro',
    city_desc_holstebro: 'Länsi-Jyllannin kulttuurikeskus, jossa on monia veistoksia.',
    city_name_slagelse: 'Slagelse',
    city_desc_slagelse: 'Historiallinen kaupunki Sjellannissa, lähellä Iso-Beltin siltaa.',
    city_name_hillerod: 'Hillerød',
    city_desc_hillerod: 'Upean Frederiksborgin linnan koti.',
    city_name_sonderborg: 'Sønderborg',
    city_desc_sonderborg: 'Historiallinen kaupunki Alsin saarella, lähellä Saksan rajaa.',
    city_name_svendborg: 'Svendborg',
    city_desc_svendborg: 'Merikaupunki Fynillä, portti saaristoon.',
    city_name_hjorring: 'Hjørring',
    city_desc_hjorring: 'Vendsysselin pääkaupunki Pohjois-Jyllannissa.',
    city_name_frederikshavn: 'Frederikshavn',
    city_desc_frederikshavn: 'Tärkeä lauttasatama, joka yhdistää Tanskan Norjaan ja Ruotsiin.',
    city_name_naestved: 'Næstved',
    city_desc_naestved: 'Historiallinen kaupunki Etelä-Sjellannissa, jossa on viehättävä keskusta.',
    city_name_joensuu: 'Joensuu',
    city_desc_joensuu: 'Pohjois-Karjalan pääkaupunki, metsien ja veden kaupunki.',
    city_name_lappeenranta: 'Lappeenranta',
    city_desc_lappeenranta: 'Järvenrantakaupunki lähellä Venäjän rajaa, tunnettu linnoituksestaan.',
    city_name_hameenlinna: 'Hämeenlinna',
    city_desc_hameenlinna: 'Historiallinen kaupunki, jossa on keskiaikainen linna, Sibeliuksen syntymäpaikka.',
    city_name_vaasa: 'Vaasa',
    city_desc_vaasa: 'Rannikkokaupunki, jolla on vahva ruotsinkielinen vaikutus.',
    city_name_seinajoki: 'Seinäjoki',
    city_desc_seinajoki: 'Kaupunki, joka tunnetaan kesäfestivaaleistaan ja Aalto-arkkitehtuurista.',
    city_name_rovaniemi: 'Rovaniemi',
    city_desc_rovaniemi: 'Joulupukin virallinen kotikaupunki napapiirillä.',
    city_name_mikkeli: 'Mikkeli',
    city_desc_mikkeli: 'Kaupunki Järvi-Suomen sydämessä, tunnettu historiastaan.',
    city_name_kotka: 'Kotka',
    city_desc_kotka: 'Merikaupunki Suomenlahdella, tunnettu puistoistaan.',
    city_name_salo: 'Salo',
    city_desc_salo: 'Kaupunki, jolla on vahva historia elektroniikkateollisuudessa.',
    city_name_porvoo: 'Porvoo',
    city_desc_porvoo: 'Viehättävä historiallinen kaupunki, jossa on punaisia puutaloja.',
    city_name_gardabaer: 'Garðabær',
    city_desc_gardabaer: 'Kasvava kunta pääkaupunkiseudulla.',
    city_name_mosfellsbaer: 'Mosfellsbær',
    city_desc_mosfellsbaer: 'Kaupunki, joka tunnetaan luonnonkauneudestaan ja vaellusreiteistään.',
    city_name_akranes: 'Akranes',
    city_desc_akranes: 'Satamakaupunki, jolla on pitkä kalastus- ja teollisuushistoria.',
    city_name_selfoss: 'Selfoss',
    city_desc_selfoss: 'Etelä-Islannin suurin kaupunki, alueen keskus.',
    city_name_seltjarnarnes: 'Seltjarnarnes',
    city_desc_seltjarnarnes: 'Pieni kaupunki niemimaalla Reykjavíkin vieressä.',
    city_name_vestmannaeyjar: 'Vestmannasaaret',
    city_desc_vestmannaeyjar: 'Saaristo etelärannikon edustalla, kuuluisa tulivuoristaan.',
    city_name_isafjordur: 'Ísafjörður',
    city_desc_isafjordur: 'Länsivuonojen suurin kaupunki, jyrkkien vuorten ympäröimä.',
    city_name_saudarkrokur: 'Sauðárkrókur',
    city_desc_saudarkrokur: 'Kaupunki Pohjois-Islannissa, tunnettu historiastaan ja hevosistaan.',
    city_name_egilsstadir: 'Egilsstaðir',
    city_desc_egilsstadir: 'Itä-Islannin pääkeskus, joka sijaitsee joen rannalla.',
    city_name_husavik: 'Húsavík',
    city_desc_husavik: 'Islannin valasmatkailun pääkaupunki.',
  },
  IS: {
    management: 'Stjórnun',
    inventory: 'Birgðir',
    shop: 'Búð',
    travel: 'Ferðast',
    staff: 'Starfsfólk',
    budget: 'Fjárhagsáætlun',
    settings: 'Stillingar',
    open_park: 'Opna garðinn',
    close_park: 'Loka garðinum',
    park_closed: 'Garðurinn er lokaður',
    park_open: 'Garðurinn er opinn',
    money: 'Peningar',
    visitors: 'Gestir',
    happiness: 'Hamingja',
    day: 'Dagur',
    weather: 'Veður',
    travel_to: 'Ferðast til',
    current_location: 'Núverandi staðsetning',
    home_city: 'Heimaborg',
    dismantle_first: 'Taka niður fyrst',
    island_locked: 'Eyja læst',
    apply_now: 'Sækja um núna',
    total_income: 'Heildartekjur',
    total_expenses: 'Heildarútgjöld',
    net_profit: 'Hagnaður',
    language: 'Tungumál',
    music_volume: 'Tónlistarstyrkur',
    sfx_volume: 'Hljóðstyrkur',
    reset_game: 'Endurstilla leik',
    confirm_reset: 'Ertu viss um að þú viljir endurstilla? Allar framfarir glatast.',
    cancel: 'Hætta við',
    confirm: 'Staðfesta',
    city_name_tromso: 'Tromsø',
    city_desc_tromso: 'Gáttin að norðurslóðum, fræg fyrir norðurljósin.',
    city_name_bodo: 'Bodø',
    city_desc_bodo: 'Borg rétt norðan við heimskautsbaug, þekkt fyrir mikinn vind.',
    city_name_sandefjord: 'Sandefjord',
    city_desc_sandefjord: 'Strandborg með ríka hvalveiðisögu.',
    city_name_larvik: 'Larvik',
    city_desc_larvik: 'Strandbær þekktur fyrir náttúrulegar uppsprettur og beykiskóg.',
    city_name_arendal: 'Arendal',
    city_desc_arendal: 'Heillandi strandbær með fallegum eyjaklasa.',
    city_name_tonsberg: 'Tønsberg',
    city_desc_tonsberg: 'Elsta borg Noregs, með ríka víkingaarfleifð.',
    city_name_porsgrunn: 'Porsgrunn',
    city_desc_porsgrunn: 'Iðnaðarborg þekkt fyrir postulínsverksmiðju sína.',
    city_name_haugesund: 'Haugesund',
    city_desc_haugesund: 'Strandborg þekkt fyrir víkingasögu sína og kvikmyndahátíð.',
    city_name_moss: 'Moss',
    city_desc_moss: 'Strandborg með ríka iðnaðar- og listhefð.',
    city_name_hamar: 'Hamar',
    city_desc_hamar: 'Staðsett við bakka Mjøsa, þekkt fyrir dómkirkjurústir sínar.',
    city_name_karlstad: 'Karlstad',
    city_desc_karlstad: 'Borg sólskinsins við bakka vatnsins Vänern.',
    city_name_vaxjo: 'Växjö',
    city_desc_vaxjo: 'Grænasta borg Evrópu, umvafin vötnum og skógum.',
    city_name_halmstad: 'Halmstad',
    city_desc_halmstad: 'Vinsæll sumarstaður með fallegum ströndum.',
    city_name_sundsvall: 'Sundsvall',
    city_desc_sundsvall: 'Steinborgin, endurbyggð úr steini eftir eyðileggjandi eldsvoða.',
    city_name_lulea: 'Luleå',
    city_desc_lulea: 'Strandborg í norðri, þekkt fyrir tækniháskóla sinn.',
    city_name_ostersund: 'Östersund',
    city_desc_ostersund: 'Vetrarborgin, staðsett við bakka vatnsins Storsjön.',
    city_name_trollhattan: 'Trollhättan',
    city_desc_trollhattan: 'Þekkt fyrir fossa sína og kvikmyndaiðnað.',
    city_name_skovde: 'Skövde',
    city_desc_skovde: 'Borg með ríka hernaðar- og iðnaðararfleifð.',
    city_name_uddevalla: 'Uddevalla',
    city_desc_uddevalla: 'Hjarta Bohuslän, með fallega strandlengju.',
    city_name_varberg: 'Varberg',
    city_desc_varberg: 'Vinsæll heilsulindarbær með sögulegu virki.',
    city_name_silkeborg: 'Silkeborg',
    city_desc_silkeborg: 'Staðsett í hjarta vatnahéraðsins, umvafið skógum.',
    city_name_fredericia: 'Fredericia',
    city_desc_fredericia: 'Söguleg virkisborg með einstöku ristarskipulagi.',
    city_name_holstebro: 'Holstebro',
    city_desc_holstebro: 'Menningarmiðstöð á Vestur-Jótlandi með mörgum höggmyndum.',
    city_name_slagelse: 'Slagelse',
    city_desc_slagelse: 'Söguleg borg á Sjálandi, nálægt Stórabeltisbrúnni.',
    city_name_hillerod: 'Hillerød',
    city_desc_hillerod: 'Heimili hins glæsilega Frederiksborgar-kastala.',
    city_name_sonderborg: 'Sønderborg',
    city_desc_sonderborg: 'Söguleg borg á eyjunni Als, nálægt þýsku landamærunum.',
    city_name_svendborg: 'Svendborg',
    city_desc_svendborg: 'Sjómannaborg á Fjóni, hliðið að eyjaklasanum.',
    city_name_hjorring: 'Hjørring',
    city_desc_hjorring: 'Aðalborg Vendsyssel á Norður-Jótlandi.',
    city_name_frederikshavn: 'Frederikshavn',
    city_desc_frederikshavn: 'Stór ferjuhöfn sem tengir Danmörku við Noreg og Svíþjóð.',
    city_name_naestved: 'Næstved',
    city_desc_naestved: 'Söguleg borg á Suður-Sjálandi með heillandi miðbæ.',
    city_name_joensuu: 'Joensuu',
    city_desc_joensuu: 'Höfuðborg Norður-Karelíu, borg skóga og vatns.',
    city_name_lappeenranta: 'Villmanstrand',
    city_desc_lappeenranta: 'Borg við vatnið nálægt rússnesku landamærunum, þekkt fyrir virki sitt.',
    city_name_hameenlinna: 'Tavastehus',
    city_desc_hameenlinna: 'Söguleg borg með miðaldakastala, fæðingarstaður Sibeliusar.',
    city_name_vaasa: 'Vasa',
    city_desc_vaasa: 'Strandborg með rík sænskumælandi áhrif.',
    city_name_seinajoki: 'Seinäjoki',
    city_desc_seinajoki: 'Borg þekkt fyrir sumarhátíðir sínar og Aalto-arkitektúr.',
    city_name_rovaniemi: 'Rovaniemi',
    city_desc_rovaniemi: 'Opinber heimaborg jólasveinsins við heimskautsbaug.',
    city_name_mikkeli: 'Sankt Michel',
    city_desc_mikkeli: 'Borg í hjarta vatnahéraðsins, þekkt fyrir sögu sína.',
    city_name_kotka: 'Kotka',
    city_desc_kotka: 'Sjómannaborg við Finnlandsflóa, þekkt fyrir garða sína.',
    city_name_salo: 'Salo',
    city_desc_salo: 'Borg með ríka sögu í rafeindaiðnaði.',
    city_name_porvoo: 'Borgá',
    city_desc_porvoo: 'Heillandi söguleg borg með rauðum timburhúsum.',
    city_name_gardabaer: 'Garðabær',
    city_desc_gardabaer: 'Vaxandi sveitarfélag á höfuðborgarsvæðinu.',
    city_name_mosfellsbaer: 'Mosfellsbær',
    city_desc_mosfellsbaer: 'Bær þekktur fyrir náttúrufegurð og gönguleiðir.',
    city_name_akranes: 'Akranes',
    city_desc_akranes: 'Hafnarbær með langa sögu um fiskveiðar og iðnað.',
    city_name_selfoss: 'Selfoss',
    city_desc_selfoss: 'Stærsti bærinn á Suðurlandi, miðstöð svæðisins.',
    city_name_seltjarnarnes: 'Seltjarnarnes',
    city_desc_seltjarnarnes: 'Lítill bær á nesi við hlið Reykjavíkur.',
    city_name_vestmannaeyjar: 'Vestmannaeyjar',
    city_desc_vestmannaeyjar: 'Eyjaklasi undan suðurströndinni, frægur fyrir eldfjöll sín.',
    city_name_isafjordur: 'Ísafjörður',
    city_desc_isafjordur: 'Stærsti bærinn á Vestfjörðum, umvafinn bröttum fjöllum.',
    city_name_saudarkrokur: 'Sauðárkrókur',
    city_desc_saudarkrokur: 'Bær á Norðurlandi, þekktur fyrir sögu sína og hesta.',
    city_name_egilsstadir: 'Egilsstaðir',
    city_desc_egilsstadir: 'Aðalmiðstöð Austurlands, staðsett við bakka fljóts.',
    city_name_husavik: 'Húsavík',
    city_desc_husavik: 'Hvalaskoðunarhöfuðborg Íslands.',
  },
  PL: {
    management: 'Zarządzanie',
    inventory: 'Ekwipunek',
    shop: 'Sklep',
    travel: 'Podróż',
    staff: 'Personel',
    budget: 'Budżet',
    settings: 'Ustawienia',
    open_park: 'Otwórz Park',
    close_park: 'Zamknij Park',
    park_closed: 'Park jest zamknięty',
    park_open: 'Park jest otwarty',
    money: 'Pieniądze',
    visitors: 'Goście',
    happiness: 'Zadowolenie',
    day: 'Dzień',
    weather: 'Pogoda',
    travel_to: 'Podróżuj do',
    current_location: 'Obecna lokalizacja',
    home_city: 'Miasto rodzinne',
    dismantle_first: 'Najpierw zdemontuj',
    island_locked: 'Wyspa zablokowana',
    apply_now: 'Aplikuj teraz',
    total_income: 'Przychód całkowity',
    total_expenses: 'Wydatki całkowite',
    net_profit: 'Zysk netto',
    language: 'Język',
    music_volume: 'Głośność muzyki',
    sfx_volume: 'Głośność efektów',
    reset_game: 'Resetuj grę',
    confirm_reset: 'Czy na pewno chcesz zresetować? Wszystkie postępy zostaną utracone.',
    cancel: 'Anuluj',
    confirm: 'Potwierdź',
  },
  RU: {
    management: 'Управление',
    inventory: 'Инвентарь',
    shop: 'Магазин',
    travel: 'Путешествие',
    staff: 'Персонал',
    budget: 'Бюджет',
    settings: 'Настройки',
    open_park: 'Открыть парк',
    close_park: 'Закрыть парк',
    park_closed: 'Парк закрыт',
    park_open: 'Парк открыт',
    money: 'Деньги',
    visitors: 'Посетители',
    happiness: 'Счастье',
    day: 'День',
    weather: 'Погода',
    travel_to: 'Путешествие в',
    current_location: 'Текущее местоположение',
    home_city: 'Родной город',
    dismantle_first: 'Сначала демонтируйте',
    island_locked: 'Остров заблокирован',
    apply_now: 'Подать заявку',
    total_income: 'Общий доход',
    total_expenses: 'Общие расходы',
    net_profit: 'Чистая прибыль',
    language: 'Язык',
    music_volume: 'Громкость музыки',
    sfx_volume: 'Громкость эффектов',
    reset_game: 'Сбросить игру',
    confirm_reset: 'Вы уверены, что хотите сбросить игру? Весь прогресс будет потерян.',
    cancel: 'Отмена',
    confirm: 'Подтвердить',
  },
  TR: {
    management: 'Yönetim',
    inventory: 'Envanter',
    shop: 'Mağaza',
    travel: 'Seyahat',
    staff: 'Personel',
    budget: 'Bütçe',
    settings: 'Ayarlar',
    open_park: 'Parkı Aç',
    close_park: 'Parkı Kapat',
    park_closed: 'Park Kapalı',
    park_open: 'Park Açık',
    money: 'Para',
    visitors: 'Ziyaretçiler',
    happiness: 'Mutluluk',
    day: 'Gün',
    weather: 'Hava Durumu',
    travel_to: 'Seyahat et:',
    current_location: 'Mevcut Konum',
    home_city: 'Ana Şehir',
    dismantle_first: 'Önce Sökün',
    island_locked: 'Ada Kilitli',
    apply_now: 'Şimdi Başvur',
    total_income: 'Toplam Gelir',
    total_expenses: 'Toplam Gider',
    net_profit: 'Net Kar',
    language: 'Dil',
    music_volume: 'Müzik Sesi',
    sfx_volume: 'Efekt Sesi',
    reset_game: 'Oyunu Sıfırla',
    confirm_reset: 'Sıfırlamak istediğinizden emin misiniz? Tüm ilerleme kaybolacak.',
    cancel: 'İptal',
    confirm: 'Onayla',
  },
  EL: {
    management: 'Διαχείριση',
    inventory: 'Απόθεμα',
    shop: 'Κατάστημα',
    travel: 'Ταξίδι',
    staff: 'Προσωπικό',
    budget: 'Προϋπολογισμός',
    settings: 'Ρυθμίσεις',
    open_park: 'Άνοιγμα Πάρκου',
    close_park: 'Κλείσιμο Πάρκου',
    park_closed: 'Το πάρκο είναι κλειστό',
    park_open: 'Το πάρκο είναι ανοιχτό',
    money: 'Χρήματα',
    visitors: 'Επισκέπτες',
    happiness: 'Ευτυχία',
    day: 'Ημέρα',
    weather: 'Καιρός',
    travel_to: 'Ταξίδι προς',
    current_location: 'Τρέχουσα Τοποθεσία',
    home_city: 'Πατρίδα',
    dismantle_first: 'Αποσυναρμολόγηση Πρώτα',
    island_locked: 'Νησί Κλειδωμένο',
    apply_now: 'Αίτηση Τώρα',
    total_income: 'Συνολικά Έσοδα',
    total_expenses: 'Συνολικά Έξοδα',
    net_profit: 'Καθαρό Κέρδος',
    language: 'Γλώσσα',
    music_volume: 'Ένταση Μουσικής',
    sfx_volume: 'Ένταση Εφέ',
    reset_game: 'Επαναφορά Παιχνιδιού',
    confirm_reset: 'Είστε σίγουροι ότι θέλετε επαναφορά; Όλη η πρόοδος θα χαθεί.',
    cancel: 'Ακύρωση',
    confirm: 'Επιβεβαίωση',
  },
  CS: {
    management: 'Správa',
    inventory: 'Inventář',
    shop: 'Obchod',
    travel: 'Cestování',
    staff: 'Personál',
    budget: 'Rozpočet',
    settings: 'Nastavení',
    open_park: 'Otevřít park',
    close_park: 'Zavřít park',
    park_closed: 'Park je zavřený',
    park_open: 'Park je otevřený',
    money: 'Peníze',
    visitors: 'Návštěvníci',
    happiness: 'Spokojenost',
    day: 'Den',
    weather: 'Počasí',
    travel_to: 'Cestovat do',
    current_location: 'Aktuální poloha',
    home_city: 'Domovské město',
    dismantle_first: 'Nejdříve demontovat',
    island_locked: 'Ostrov uzamčen',
    apply_now: 'Požádat nyní',
    total_income: 'Celkové příjmy',
    total_expenses: 'Celkové výdaje',
    net_profit: 'Čistý zisk',
    language: 'Jazyk',
    music_volume: 'Hlasitost hudby',
    sfx_volume: 'Hlasitost efektů',
    reset_game: 'Resetovat hru',
    confirm_reset: 'Opravdu chcete resetovat? Veškerý postup bude ztracen.',
    cancel: 'Zrušit',
    confirm: 'Potvrdit',
  },
  HU: {
    management: 'Kezelés',
    inventory: 'Leltár',
    shop: 'Bolt',
    travel: 'Utazás',
    staff: 'Személyzet',
    budget: 'Költségvetés',
    settings: 'Beállítások',
    open_park: 'Park megnyitása',
    close_park: 'Park bezárása',
    park_closed: 'A park zárva van',
    park_open: 'A park nyitva van',
    money: 'Pénz',
    visitors: 'Látogatók',
    happiness: 'Boldogság',
    day: 'Nap',
    weather: 'Időjárás',
    travel_to: 'Utazás ide:',
    current_location: 'Jelenlegi helyszín',
    home_city: 'Szülőváros',
    dismantle_first: 'Először szét kell szerelni',
    island_locked: 'Sziget lezárva',
    apply_now: 'Jelentkezés most',
    total_income: 'Összes bevétel',
    total_expenses: 'Összes kiadás',
    net_profit: 'Nettó nyereség',
    language: 'Nyelv',
    music_volume: 'Zene hangereje',
    sfx_volume: 'Effektek hangereje',
    reset_game: 'Játék alaphelyzetbe állítása',
    confirm_reset: 'Biztosan alaphelyzetbe állítja? Minden haladás elvész.',
    cancel: 'Mégse',
    confirm: 'Megerősítés',
  },
  RO: {
    management: 'Management',
    inventory: 'Inventar',
    shop: 'Magazin',
    travel: 'Călătorie',
    staff: 'Personal',
    budget: 'Buget',
    settings: 'Setări',
    open_park: 'Deschide Parcul',
    close_park: 'Închide Parcul',
    park_closed: 'Parcul este închis',
    park_open: 'Parcul este deschis',
    money: 'Bani',
    visitors: 'Vizitatori',
    happiness: 'Fericire',
    day: 'Zi',
    weather: 'Vreme',
    travel_to: 'Călătorește la',
    current_location: 'Locație Actuală',
    home_city: 'Oraș Natal',
    dismantle_first: 'Dezmembrează întâi',
    island_locked: 'Insulă Blocată',
    apply_now: 'Aplică Acum',
    total_income: 'Venit Total',
    total_expenses: 'Cheltuieli Totale',
    net_profit: 'Profit Net',
    language: 'Limbă',
    music_volume: 'Volum Muzică',
    sfx_volume: 'Volum Efecte',
    reset_game: 'Resetează Jocul',
    confirm_reset: 'Ești sigur că vrei să resetezi? Tot progresul va fi pierdut.',
    cancel: 'Anulează',
    confirm: 'Confirmă',
  },
  BG: {
    management: 'Управление',
    inventory: 'Инвентар',
    shop: 'Магазин',
    travel: 'Пътуване',
    staff: 'Персонал',
    budget: 'Бюджет',
    settings: 'Настройки',
    open_park: 'Отвори парка',
    close_park: 'Затвори парка',
    park_closed: 'Паркът е затворен',
    park_open: 'Паркът е отворен',
    money: 'Пари',
    visitors: 'Посетители',
    happiness: 'Щастие',
    day: 'Ден',
    weather: 'Време',
    travel_to: 'Пътуване до',
    current_location: 'Текущо местоположение',
    home_city: 'Роден град',
    dismantle_first: 'Първо демонтирайте',
    island_locked: 'Островът е блокиран',
    apply_now: 'Кандидатствай сега',
    total_income: 'Общ доход',
    total_expenses: 'Общи разходи',
    net_profit: 'Чиста печалба',
    language: 'Език',
    music_volume: 'Сила на музиката',
    sfx_volume: 'Сила на ефектите',
    reset_game: 'Нулиране на играта',
    confirm_reset: 'Сигурни ли сте, че искате да нулирате? Целият прогрес ще бъде загубен.',
    cancel: 'Отказ',
    confirm: 'Потвърди',
  },
  HR: {
    management: 'Upravljanje',
    inventory: 'Inventar',
    shop: 'Trgovina',
    travel: 'Putovanje',
    staff: 'Osoblje',
    budget: 'Proračun',
    settings: 'Postavke',
    open_park: 'Otvori park',
    close_park: 'Zatvori park',
    park_closed: 'Park je zatvoren',
    park_open: 'Park je otvoren',
    money: 'Novac',
    visitors: 'Posjetitelji',
    happiness: 'Sreća',
    day: 'Dan',
    weather: 'Vrijeme',
    travel_to: 'Putuj u',
    current_location: 'Trenutna lokacija',
    home_city: 'Rodni grad',
    dismantle_first: 'Prvo rastavi',
    island_locked: 'Otok zaključan',
    apply_now: 'Prijavi se sada',
    total_income: 'Ukupni prihod',
    total_expenses: 'Ukupni troškovi',
    net_profit: 'Neto dobit',
    language: 'Jezik',
    music_volume: 'Glasnoća glazbe',
    sfx_volume: 'Glasnoća efekata',
    reset_game: 'Resetiraj igru',
    confirm_reset: 'Jeste li sigurni da želite resetirati? Sav napredak će biti izgubljen.',
    cancel: 'Odustani',
    confirm: 'Potvrdi',
  },
  SK: {
    management: 'Správa',
    inventory: 'Inventár',
    shop: 'Obchod',
    travel: 'Cestovanie',
    staff: 'Personál',
    budget: 'Rozpočet',
    settings: 'Nastavenia',
    open_park: 'Otvoriť park',
    close_park: 'Zatvoriť park',
    park_closed: 'Park je zatvorený',
    park_open: 'Park je otvorený',
    money: 'Peniaze',
    visitors: 'Návštevníci',
    happiness: 'Spokojnosť',
    day: 'Deň',
    weather: 'Počasie',
    travel_to: 'Cestovať do',
    current_location: 'Aktuálna poloha',
    home_city: 'Domovské mesto',
    dismantle_first: 'Najskôr demontovať',
    island_locked: 'Ostrov uzamknutý',
    apply_now: 'Požiadať teraz',
    total_income: 'Celkové príjmy',
    total_expenses: 'Celkové výdavky',
    net_profit: 'Čistý zisk',
    language: 'Jazyk',
    music_volume: 'Hlasitosť hudby',
    sfx_volume: 'Hlasitosť efektov',
    reset_game: 'Resetovať hru',
    confirm_reset: 'Naozaj chcete resetovať? Všetok postup bude stratený.',
    cancel: 'Zrušiť',
    confirm: 'Potvrdiť',
  },
  SL: {
    management: 'Upravljanje',
    inventory: 'Inventar',
    shop: 'Trgovina',
    travel: 'Potovanje',
    staff: 'Osebje',
    budget: 'Proračun',
    settings: 'Nastavitve',
    open_park: 'Odpri park',
    close_park: 'Zapri park',
    park_closed: 'Park je zaprt',
    park_open: 'Park je odprt',
    money: 'Denar',
    visitors: 'Obiskovalci',
    happiness: 'Sreča',
    day: 'Dan',
    weather: 'Vreme',
    travel_to: 'Potuj v',
    current_location: 'Trenutna lokacija',
    home_city: 'Domače mesto',
    dismantle_first: 'Najprej razstavi',
    island_locked: 'Otok zaklenjen',
    apply_now: 'Prijavi se zdaj',
    total_income: 'Skupni prihodki',
    total_expenses: 'Skupni odhodki',
    net_profit: 'Čisti dobiček',
    language: 'Jezik',
    music_volume: 'Glasnost glasbe',
    sfx_volume: 'Glasnost učinkov',
    reset_game: 'Ponastavi igro',
    confirm_reset: 'Ali ste prepričani, da želite ponastaviti? Ves napredek bo izgubljen.',
    cancel: 'Prekliči',
    confirm: 'Potrdi',
  },
  ET: {
    management: 'Haldamine',
    inventory: 'Inventar',
    shop: 'Pood',
    travel: 'Reisimine',
    staff: 'Personal',
    budget: 'Eelarve',
    settings: 'Seaded',
    open_park: 'Ava park',
    close_park: 'Sulge park',
    park_closed: 'Park on suletud',
    park_open: 'Park on avatud',
    money: 'Raha',
    visitors: 'Külastajad',
    happiness: 'Õnn',
    day: 'Päev',
    weather: 'Ilm',
    travel_to: 'Reisi sihtkohta',
    current_location: 'Praegune asukoht',
    home_city: 'Kodulinn',
    dismantle_first: 'Demonteeri esmalt',
    island_locked: 'Saar lukustatud',
    apply_now: 'Kandideeri kohe',
    total_income: 'Kogutulu',
    total_expenses: 'Kogukulud',
    net_profit: 'Netokasum',
    language: 'Keel',
    music_volume: 'Muusika helitugevus',
    sfx_volume: 'Efektide helitugevus',
    reset_game: 'Lähtesta mäng',
    confirm_reset: 'Kas olete kindel, et soovite lähtestada? Kogu progress kaob.',
    cancel: 'Tühista',
    confirm: 'Kinnita',
  },
  LV: {
    management: 'Pārvaldība',
    inventory: 'Inventārs',
    shop: 'Veikals',
    travel: 'Ceļošana',
    staff: 'Personāls',
    budget: 'Budžets',
    settings: 'Iestatījumi',
    open_park: 'Atvērt parku',
    close_park: 'Aizvērt parku',
    park_closed: 'Parks ir slēgts',
    park_open: 'Parks ir atvērts',
    money: 'Nauda',
    visitors: 'Apmeklētāji',
    happiness: 'Laime',
    day: 'Diena',
    weather: 'Laikapstākļi',
    travel_to: 'Ceļot uz',
    current_location: 'Pašreizējā atrašanās vieta',
    home_city: 'Dzimtā pilsēta',
    dismantle_first: 'Vispirms demontēt',
    island_locked: 'Sala bloķēta',
    apply_now: 'Pieteikties tagad',
    total_income: 'Kopējie ienākumi',
    total_expenses: 'Kopējie izdevumi',
    net_profit: 'Tīrā peļņa',
    language: 'Valoda',
    music_volume: 'Mūzikas skaļums',
    sfx_volume: 'Efektu skaļums',
    reset_game: 'Atiestatīt spēli',
    confirm_reset: 'Vai tiešām vēlaties atiestatīt? Viss progress tiks zaudēts.',
    cancel: 'Atcelt',
    confirm: 'Apstiprināt',
  },
  LT: {
    management: 'Valdymas',
    inventory: 'Inventorius',
    shop: 'Parduotuvė',
    travel: 'Kelionės',
    staff: 'Personalas',
    budget: 'Biudžetas',
    settings: 'Nustatymai',
    open_park: 'Atidaryti parką',
    close_park: 'Uždaryti parką',
    park_closed: 'Parkas uždarytas',
    park_open: 'Parkas atidarytas',
    money: 'Pinigai',
    visitors: 'Lankytojai',
    happiness: 'Laimė',
    day: 'Diena',
    weather: 'Orai',
    travel_to: 'Keliauti į',
    current_location: 'Dabartinė vieta',
    home_city: 'Gimtasis miestas',
    dismantle_first: 'Pirmiausia išmontuoti',
    island_locked: 'Sala užrakinta',
    apply_now: 'Pateikti paraišką',
    total_income: 'Visos pajamos',
    total_expenses: 'Visos išlaidos',
    net_profit: 'Grynasis pelnas',
    language: 'Kalba',
    music_volume: 'Muzikos garsumas',
    sfx_volume: 'Efektų garsumas',
    reset_game: 'Anuliuoti žaidimą',
    confirm_reset: 'Ar tikrai norite anuliuoti? Visa pažanga bus prarasta.',
    cancel: 'Atšaukti',
    confirm: 'Patvirtinti',
  },
  MT: {
    management: 'Ġestjoni',
    inventory: 'Inventarju',
    shop: 'Ħanut',
    travel: 'Ivvjaġġar',
    staff: 'Staff',
    budget: 'Baġit',
    settings: 'Settings',
    open_park: 'Iftaħ il-Park',
    close_park: 'Agħlaq il-Park',
    park_closed: 'Il-Park huwa Magħluq',
    park_open: 'Il-Park huwa Miftuħ',
    money: 'Flus',
    visitors: 'Viżitaturi',
    happiness: 'Hena',
    day: 'Jum',
    weather: 'Temp',
    travel_to: 'Ivvjaġġa lejn',
    current_location: 'Post Attwali',
    home_city: 'Belt tat-Twelid',
    dismantle_first: 'Żarma l-Ewwel',
    island_locked: 'Gżira Makkjata',
    apply_now: 'Applika Issa',
    total_income: 'Dħul Totali',
    total_expenses: 'Spejjeż Totali',
    net_profit: 'Profitt Nett',
    language: 'Lingwa',
    music_volume: 'Volum tal-Mużika',
    sfx_volume: 'Volum tas-SFX',
    reset_game: 'Irrisettja l-Logħba',
    confirm_reset: 'Żgur li trid tirrisettja? Il-progress kollu jintilef.',
    cancel: 'Ikkanċella',
    confirm: 'Ikkonferma',
  },
  GA: {
    management: 'Bainistíocht',
    inventory: 'Fardal',
    shop: 'Siopa',
    travel: 'Taisteal',
    staff: 'Foireann',
    budget: 'Buiséad',
    settings: 'Socruithe',
    open_park: 'Oscail an Pháirc',
    close_park: 'Dún an Pháirc',
    park_closed: 'Tá an Pháirc Dúnta',
    park_open: 'Tá an Pháirc Oscailte',
    money: 'Airgead',
    visitors: 'Cuairteoirí',
    happiness: 'Sonas',
    day: 'Lá',
    weather: 'Aimsir',
    travel_to: 'Taisteal go',
    current_location: 'Suíomh Reatha',
    home_city: 'Baile Dúchais',
    dismantle_first: 'Díchóimeáil ar dtús',
    island_locked: 'Oileán faoi ghlas',
    apply_now: 'Cuir isteach anois',
    total_income: 'Ioncam Iomlán',
    total_expenses: 'Costais Iomlána',
    net_profit: 'Brabús Glan',
    language: 'Teanga',
    music_volume: 'Airde Ceoil',
    sfx_volume: 'Airde SFX',
    reset_game: 'Athshocraigh an Cluiche',
    confirm_reset: 'An bhfuil tú cinnte gur mhaith leat athshocrú? Caillfear gach dul chun cinn.',
    cancel: 'Cealaigh',
    confirm: 'Deimhnigh',
  },
  CY: {
    management: 'Rheoli',
    inventory: 'Inventori',
    shop: 'Siop',
    travel: 'Teithio',
    staff: 'Staff',
    budget: 'Cyllideb',
    settings: 'Gosodiadau',
    open_park: 'Agor y Parc',
    close_park: 'Cau\'r Parc',
    park_closed: 'Mae\'r Parc ar Gau',
    park_open: 'Mae\'r Parc ar Agor',
    money: 'Arian',
    visitors: 'Ymwelwyr',
    happiness: 'Hapusrwydd',
    day: 'Diwrnod',
    weather: 'Tywydd',
    travel_to: 'Teithio i',
    current_location: 'Lleoliad Presennol',
    home_city: 'Tref Enedigol',
    dismantle_first: 'Dadosod yn Gyntaf',
    island_locked: 'Ynys wedi\'i Chloi',
    apply_now: 'Gwneud Cais Nawr',
    total_income: 'Cyfanswm Incwm',
    total_expenses: 'Cyfanswm Treuliau',
    net_profit: 'Elw Net',
    language: 'Iaith',
    music_volume: 'Lefel Cerddoriaeth',
    sfx_volume: 'Lefel SFX',
    reset_game: 'Ailosod y Gêm',
    confirm_reset: 'Ydych chi\'n siŵr eich bod am ailosod? Bydd yr holl gynnydd yn cael ei golli.',
    cancel: 'Canslo',
    confirm: 'Cadarnhau',
  },
  SQ: {
    management: 'Menaxhimi',
    inventory: 'Inventari',
    shop: 'Dyqani',
    travel: 'Udhëtimi',
    staff: 'Stafi',
    budget: 'Buxheti',
    settings: 'Cilësimet',
    open_park: 'Hapni Parkun',
    close_park: 'Mbyllni Parkun',
    park_closed: 'Parku është i mbyllur',
    park_open: 'Parku është i hapur',
    money: 'Para',
    visitors: 'Vizitorët',
    happiness: 'Lumturia',
    day: 'Dita',
    weather: 'Moti',
    travel_to: 'Udhëto drejt',
    current_location: 'Vendndodhja aktuale',
    home_city: 'Qyteti i lindjes',
    dismantle_first: 'Çmontoni së pari',
    island_locked: 'Ishulli i bllokuar',
    apply_now: 'Apliko tani',
    total_income: 'Të ardhurat totale',
    total_expenses: 'Shpenzimet totale',
    net_profit: 'Fitimi neto',
    language: 'Gjuha',
    music_volume: 'Volumi i muzikës',
    sfx_volume: 'Volumi i efekteve',
    reset_game: 'Rifillo lojën',
    confirm_reset: 'A jeni të sigurt që dëshironi të rifilloni? I gjithë progresi do të humbasë.',
    cancel: 'Anulo',
    confirm: 'Konfirmo',
  },
  MK: {
    management: 'Управување',
    inventory: 'Инвентар',
    shop: 'Продавница',
    travel: 'Патување',
    staff: 'Персонал',
    budget: 'Буџет',
    settings: 'Поставки',
    open_park: 'Отвори го паркот',
    close_park: 'Затвори го паркот',
    park_closed: 'Паркот е затворен',
    park_open: 'Паркот е отворен',
    money: 'Пари',
    visitors: 'Посетители',
    happiness: 'Среќа',
    day: 'Ден',
    weather: 'Време',
    travel_to: 'Патувај во',
    current_location: 'Тековна локација',
    home_city: 'Роден град',
    dismantle_first: 'Прво демонтирајте',
    island_locked: 'Островот е заклучен',
    apply_now: 'Аплицирај сега',
    total_income: 'Вкупен приход',
    total_expenses: 'Вкупни трошоци',
    net_profit: 'Нето добивка',
    language: 'Јазик',
    music_volume: 'Јачина на музика',
    sfx_volume: 'Јачина на ефекти',
    reset_game: 'Ресетирај ја играта',
    confirm_reset: 'Дали сте сигурни дека сакате да ресетирате? Целиот напредок ќе биде изгубен.',
    cancel: 'Откажи',
    confirm: 'Потврди',
  },
};
